<a href="https://colab.research.google.com/github/cbonnin88/Python-For-Product/blob/main/EV_Charging_Network_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The Product:** A network of EV charging stations.

**The Goal:** Understand user engagement, optimize the station experience, and identify areas with high friction (long wait times).

**Core Product Metrics We'll Track:**

- Usage / Engagement: Total charging sessions, Energy consumed.

- User Friction: Waiting time, Queue length.

- Segment Behavior: Performance across different location types (Urban vs. Highway) and vehicle types.

# **Phase 1: Data Cleaning (with Polars)**

In [ ]:
import polars as pl
import gdown as gd
import plotly.express as px

In [ ]:
url = 'https://drive.google.com/uc?id=1cOi_3aElYDe4G4w6Yyu7mve3zG0z41hU'

In [ ]:
file_path = gd.download(url,'charging_ev_and_grid_opitmization_dataset.csv',quiet=True)

In [ ]:
df_ev = pl.read_csv(file_path)

In [ ]:
display(df_ev.head())

shape: (5, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ station_i ┆ location_ ┆ vehicle_i ┆ … ┆ charging_ ┆ assigned_ ┆ charging_ ┆ optimiza │
│ ---       ┆ d         ┆ type      ┆ d         ┆   ┆ demand    ┆ charger_i ┆ priority  ┆ tion_rew │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ d         ┆ ---       ┆ ard      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1/1/2025  ┆ ST004     ┆ Urban     ┆ EV10000   ┆ … ┆ 17.242398 ┆ CH4       ┆ Low       ┆ -8.62229 │
│ 0:00      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ 1/1/2025  ┆ ST005     ┆ Urban     ┆ EV10001   ┆ … ┆ 18.324933 ┆ CH9       ┆ Low       ┆ -1.93564 │
│ 0:15      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 1/1/2025  ┆ ST019     ┆ Highway   ┆ EV10002   ┆ … ┆ 36.028168 ┆ CH2       ┆ Low       ┆ -18.2018 │
│ 0:30      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 46       │
│ 1/1/2025  ┆ ST008     ┆ Urban     ┆ EV10003   ┆ … ┆ 17.146935 ┆ CH9       ┆ Medium    ┆ -7.40401 │
│ 0:45      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 1/1/2025  ┆ ST008     ┆ Highway   ┆ EV10004   ┆ … ┆ 14.577768 ┆ CH1       ┆ Low       ┆ -6.57746 │
│ 1:00      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
print(f'Original Data Shape: {df_ev.shape}')

Original Data Shape: (8354, 27)

In [ ]:
# Data Cleaning & Feature Engineeering

clean_df = (
    df_ev
    .with_columns([
        pl.col('timestamp').str.strptime(pl.Datetime,format='%m/%d/%Y %H:%M',strict=False).alias('timestamp'),
        pl.col('arrival_time').str.strptime(pl.Datetime,format='%m/%d/%Y %H:%M',strict=False).alias('arrival_time'),
        pl.col('charging_start_time').str.strptime(pl.Datetime, format='%m/%d/%Y %H:%M',strict=False).alias('charging_start_time')
    ])
    .with_columns([
        pl.col('timestamp').dt.date().alias('date')
    ])
    .drop_nulls(subset=['timestamp'])
)

display(clean_df.glimpse())

Rows: 8354
Columns: 28
$ timestamp              <datetime[μs]> 2025-01-01 00:00:00, 2025-01-01 00:15:00, 2025-01-01 00:30:00, 2025-01-01 00:45:00, 2025-01-01 01:00:00, 2025-01-01 01:15:00, 2025-01-01 01:30:00, 2025-01-01 01:45:00, 2025-01-01 02:00:00, 2025-01-01 02:15:00
$ station_id                      <str> 'ST004', 'ST005', 'ST019', 'ST008', 'ST008', 'ST014', 'ST004', 'ST020', 'ST004', 'ST020'
$ location_type                   <str> 'Urban', 'Urban', 'Highway', 'Urban', 'Highway', 'Highway', 'Urban', 'Highway', 'Highway', 'Highway'
$ vehicle_id                      <str> 'EV10000', 'EV10001', 'EV10002', 'EV10003', 'EV10004', 'EV10005', 'EV10006', 'EV10007', 'EV10008', 'EV10009'
$ vehicle_type                    <str> 'Two-Wheeler', 'Two-Wheeler', 'Car', 'Two-Wheeler', 'Two-Wheeler', 'Bus', 'Bus', 'Car', 'Car', 'Two-Wheeler'
$ arrival_time           <datetime[μs]> 2025-01-01 00:00:00, 2025-01-01 00:15:00, 2025-01-01 00:30:00, 2025-01-01 00:45:00, 2025-01-01 01:00:00, 2025-01-01 01:15:00, 2025-01-01 01:30:00, 2025-01-01 01:45:00, 2025-01-01 02:00:00, 2025-01-01 02:15:00
$ charging_start_time    <datetime[μs]> 2025-01-01 00:12:00, 2025-01-01 00:23:00, 2025-01-01 00:41:00, 2025-01-01 00:54:00, 2025-01-01 01:08:00, 2025-01-01 01:18:00, 2025-01-01 01:51:00, 2025-01-01 01:49:00, 2025-01-01 02:02:00, 2025-01-01 02:16:00
$ charging_end_time               <str> '1/1/2025 4:33', '1/1/2025 1:12', '1/1/2025 1:35', '1/1/2025 3:29', '1/1/2025 6:14', '1/1/2025 2:15', '1/1/2025 2:23', '1/1/2025 2:51', '1/1/2025 3:11', '1/1/2025 3:59'
$ waiting_time                    <i64> 12, 8, 11, 9, 8, 3, 21, 4, 2, 1
$ battery_capacity_kWh            <i64> 60, 100, 75, 40, 75, 75, 30, 60, 100, 60
$ initial_soc                     <f64> 48.98455001, 58.49549261, 35.71172192, 29.27082513, 25.5855538, 39.89499894, 24.04672548, 19.9421202, 46.48030892, 36.13664147
$ final_soc                       <f64> 99.86557637, 100.0, 95.73346388, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.54003543
$ energy_consumed_kWh             <f64> 30.52861582, 41.50450739, 45.01630647, 28.29166995, 55.81083465, 45.07875079, 22.78598235, 48.03472788, 53.51969108, 38.04203638
$ charging_power_kW               <i64> 7, 50, 50, 11, 11, 50, 50, 50, 50, 22
$ charging_duration               <f64> 261.6738499, 49.916518, 54.01956776, 155.7733697, 306.369479, 57.82379866, 32.69810476, 62.1133351, 69.72186418, 103.7510083
$ queue_length                    <i64> 4, 3, 8, 3, 5, 0, 2, 7, 6, 2
$ station_load                    <f64> 15.16167224, 20.99721943, 31.60615077, 21.80304987, 15.62626585, 20.4166852, 15.30533878, 18.48089303, 23.6585375, 16.03438405
$ electricity_price               <f64> 13.66, 5.47, 9.5, 6.22, 13.42, 14.61, 5.16, 8.58, 14.72, 13.96
$ renewable_energy_ratio          <f64> 0.280334504, 0.392126656, 0.103979488, 0.248553073, 0.23492624, 0.353360155, 0.227020444, 0.134760718, 0.354674147, 0.242611067
$ traffic_density                 <str> 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low', 'Low'
$ weather_condition               <str> 'Cloudy', 'Rainy', 'Clear', 'Clear', 'Cloudy', 'Clear', 'Clear', 'Rainy', 'Rainy', 'Clear'
$ day_of_week                     <str> 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday'
$ time_slot                       <str> 'Off-Peak', 'Off-Peak', 'Off-Peak', 'Off-Peak', 'Off-Peak', 'Off-Peak', 'Off-Peak', 'Off-Peak', 'Off-Peak', 'Off-Peak'
$ charging_demand                 <f64> 17.24239802, 18.32493284, 36.02816833, 17.14693509, 14.57776821, 22.8898863, 14.25415396, 22.11192729, 25.87583271, 16.66713977
$ assigned_charger_id             <str> 'CH4', 'CH9', 'CH2', 'CH9', 'CH1', 'CH4', 'CH6', 'CH8', 'CH5', 'CH2'
$ charging_priority               <str> 'Low', 'Low', 'Low', 'Medium', 'Low', 'Medium', 'Medium', 'High', 'High', 'Low'
$ optimization_reward             <f64> -8.622299343, -1.935644217, -18.2018455, -7.404017784, -6.577465969, 3.517467598, -18.25045443, -7.153357071, 0.908516919, 2.071455199
$ date                           <date> 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01

None

In [ ]:
display(clean_df.head())

shape: (5, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ station_i ┆ location_ ┆ vehicle_i ┆ … ┆ assigned_ ┆ charging_ ┆ optimizat ┆ date     │
│ ---       ┆ d         ┆ type      ┆ d         ┆   ┆ charger_i ┆ priority  ┆ ion_rewar ┆ ---      │
│ datetime[ ┆ ---       ┆ ---       ┆ ---       ┆   ┆ d         ┆ ---       ┆ d         ┆ date     │
│ μs]       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-01-0 ┆ ST004     ┆ Urban     ┆ EV10000   ┆ … ┆ CH4       ┆ Low       ┆ -8.622299 ┆ 2025-01- │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-01-0 ┆ ST005     ┆ Urban     ┆ EV10001   ┆ … ┆ CH9       ┆ Low       ┆ -1.935644 ┆ 2025-01- │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 00:15:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-01-0 ┆ ST019     ┆ Highway   ┆ EV10002   ┆ … ┆ CH2       ┆ Low       ┆ -18.20184 ┆ 2025-01- │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6         ┆ 01       │
│ 00:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-01-0 ┆ ST008     ┆ Urban     ┆ EV10003   ┆ … ┆ CH9       ┆ Medium    ┆ -7.404018 ┆ 2025-01- │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 00:45:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-01-0 ┆ ST008     ┆ Highway   ┆ EV10004   ┆ … ┆ CH1       ┆ Low       ┆ -6.577466 ┆ 2025-01- │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01       │
│ 01:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# **Phase 2: Exploratory Data Analysis (EDA)**

1. Engagement Metric: Daily Charging Sessions
- Are peoplle using our charging stations ?

In [ ]:
# Aggregate data using Polars: Count sessions per day
daily_usage = (
    clean_df
    .group_by('date')
    .agg(pl.len().alias('total_sessions'))
    .sort('date')
)

display(daily_usage.head())

shape: (5, 2)
┌────────────┬────────────────┐
│ date       ┆ total_sessions │
│ ---        ┆ ---            │
│ date       ┆ u32            │
╞════════════╪════════════════╡
│ 2025-01-01 ┆ 96             │
│ 2025-01-02 ┆ 96             │
│ 2025-01-03 ┆ 96             │
│ 2025-01-04 ┆ 96             │
│ 2025-01-05 ┆ 96             │
└────────────┴────────────────┘

In [ ]:
fig_daily_usage = px.line(
    daily_usage.to_pandas(),
    x='date',
    y='total_sessions',
    title='Product Engagement: Daily Charging Sessions',
    labels={'date':'Date','total_sessions':'Number of Sessions'},
    markers=True
)

fig_daily_usage.show()

2. User Friction: Average Waiting Time by Location
- Waiting time is a massive friction point in the EV user journey. If users wait too long at Urban stations vs Highway stations, we might need to build more chargers in the city.

In [ ]:
friction_df = (
    clean_df
    .group_by('location_type')
    .agg(pl.col('waiting_time').mean().alias('avg_waiting_time_mins'))
    .sort('avg_waiting_time_mins',descending=True)
)

display(friction_df)

shape: (2, 2)
┌───────────────┬───────────────────────┐
│ location_type ┆ avg_waiting_time_mins │
│ ---           ┆ ---                   │
│ str           ┆ f64                   │
╞═══════════════╪═══════════════════════╡
│ Highway       ┆ 9.598896              │
│ Urban         ┆ 9.454155              │
└───────────────┴───────────────────────┘

In [ ]:
fig_friction = px.bar(
    friction_df.to_pandas(),
    x='location_type',
    y='avg_waiting_time_mins',
    color='location_type',
    title='User Friction: Average Waiting Time by Location Type',
    labels={'location_type':'Location Type','avg_waiting_time_mins':'Average Wait Time (Minutes)'},
    color_discrete_sequence=px.colors.sequential.Viridis_r
)

fig_friction.show()

3. Value Delivered: Energy Consumed by Vehicule Type
- Different user personas (Buses vs. Cars) extract different value from our product.

In [ ]:
fig_energy_consumed = px.box(
    clean_df.to_pandas(),
    x='vehicle_type',
    y='energy_consumed_kWh',
    color='vehicle_type',
    title='Value Delivered: Energy Consumed per Sessions by Vehicle Type',
    labels = {'vehicle_type':'Vehicle Types','energy_consumed_kWh':'Energy Consumed (kWh)'}
)

fig_energy_consumed.show()

In [ ]:
clean_df.write_csv('clean_ev_charging_data.csv')
print('Clean data exported successfullly for Looker (Data) Studio')

Clean data exported successfullly for Looker (Data) Studio